// A generative AI model wrote or edited portions of this file with the supervision of a human developer and careful human review.

/**
 * Lookup + grouping helpers for the no-data categorization (dev plan §5.1).
 *
 * Data contract (generated by data/R/preprocess-no-data.R):
 *   { "<metric_id>": { "<state_fips>": "found" | "not_found" } }
 *
 * The file is sparse: any metric × state pair it doesn't cover is "not_found"
 * (settled with the data team 2026-07-08). That default lives here and only here.
 */

import { hasMetricData } from "$utils/disaggregates";

/** @typedef {"found" | "not_found"} CategoryCode */
/**
 * Values are CategoryCodes; typed as string so the imported JSON (which infers
 * plain strings) assigns without casts.
 * @typedef {Record<string, Record<string, string>>} NoDataCategories
 */

/**
 * Display bucket from page-tool.aml `[noDataBuckets]`.
 * @typedef {Object} BucketConfig
 * @property {string} value - bucket id
 * @property {string} label - bucket heading
 * @property {string} [labelSubstate] - heading used instead of `label` in a sub-state view
 * @property {string} copy - bucket description
 * @property {string} [copySubstate] - description used instead of `copy` in a sub-state view
 * @property {string} codes - comma-separated CategoryCodes the bucket includes
 * @property {string | boolean} [stateData] - "true" also routes into this bucket every
 *   metric the tool publishes for the enclosing state, whatever its code
 */

export const DEFAULT_CATEGORY = "not_found";

/**
 * Resolve the categorization code for a metric in a state.
 *
 * @param {NoDataCategories | undefined} categories
 * @param {number | string} metricId
 * @param {string | undefined} stateFips - zero-padded 2-char fips
 * @returns {string} a CategoryCode
 */
export const lookupCategory = (categories, metricId, stateFips) =>
  (stateFips && categories?.[String(metricId)]?.[stateFips]) || DEFAULT_CATEGORY;

/**
 * Whether a bucketed display is possible at all. False for a missing/empty
 * categories file or no lookup state (national view) — both fall back to the
 * flat single-list display.
 *
 * @param {NoDataCategories | undefined} categories
 * @param {string | undefined} stateFips
 * @returns {boolean}
 */
export const canBucket = (categories, stateFips) =>
  Boolean(stateFips) && Boolean(categories) && Object.keys(categories ?? {}).length > 0;

/**
 * Does the tool itself publish this metric for the enclosing state?
 *
 * A sub-state view lists metrics that are missing only because of the geography level —
 * never published at that level (m182), or suppressed for a small geography (m87) —
 * alongside metrics that are genuinely absent everywhere. The ECS codes answer a question
 * about the *state*, so bucketing on them alone puts the first group under copy that
 * asserts an absence the tool's own state view disproves. These metrics are routed to the
 * `stateData` bucket instead, whatever ECS says about them, which leaves the other bucket
 * meaning "no state-level data anywhere" — see
 * `.agent/docs/no-data-section-issues-2026-09-02.md` issue 2.
 *
 * Same three-part test as getSelectedIndicators, run against the states.json record.
 *
 * @param {Object<string, *> | undefined} stateData - the enclosing state's `data` object
 * @param {{ metric_id: number, disagg_only?: boolean, geo_states?: boolean,
 *   in_tool?: boolean }} metric - metrics.json entry
 * @returns {boolean}
 */
export const availableAtState = (stateData, metric) =>
  hasMetricData(stateData, metric) && metric.geo_states === true && metric.in_tool === true;

/**
 * Group metrics into the configured display buckets for one state, preserving bucket order.
 *
 * Two passes over the rules, in precedence order: a metric the tool publishes for the
 * enclosing state goes to the `stateData` bucket whatever ECS says about it, and everything
 * else falls to the bucket claiming its code. Both codes are claimed by a bucket and
 * uncovered pairs default to not_found, so every metric lands in exactly one bucket.
 *
 * `stateData` is the states-level view's cue to skip the first rule: there is no enclosing
 * state to be missing data relative to, so the buckets split on ECS codes alone.
 *
 * @template {{ metric_id: number }} T
 * @param {T[]} metrics - metric metadata objects (the EQ's noMetricData list)
 * @param {NoDataCategories | undefined} categories
 * @param {string | undefined} stateFips
 * @param {BucketConfig[]} buckets - `[noDataBuckets]` aml entries
 * @param {Object<string, *>} [stateData] - the enclosing state's `data` object; omitted at
 *   states level and before states.json lands
 * @returns {Array<{bucket: BucketConfig, metrics: T[]}>}
 */
export const groupMetricsByBucket = (metrics, categories, stateFips, buckets, stateData) => {
  const parsed = buckets.map((bucket) => ({
    bucket,
    codes: String(bucket.codes)
      .split(",")
      .map((code) => code.trim()),
    /** @type {T[]} */
    metrics: []
  }));
  // aml values are strings; a boolean survives the same comparison
  const stateBucket = parsed.find(
    (entry) => String(entry.bucket.stateData).trim().toLowerCase() === "true"
  );
  for (const metric of metrics) {
    if (stateData && stateBucket && availableAtState(stateData, metric)) {
      stateBucket.metrics.push(metric);
      continue;
    }
    const code = lookupCategory(categories, metric.metric_id, stateFips);
    parsed.find((entry) => entry.codes.includes(code))?.metrics.push(metric);
  }
  return parsed.map(({ bucket, metrics }) => ({ bucket, metrics }));
};
